services:
  admin-panel:
    build: .
    container_name: Admin-Panel
    ports:
      - "8080:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      # - ~/devices.db:/app/devices.db
    restart: unless-stopped
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app
