services:
  adminpanel:
    build: .
    container_name: adminpanel
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      # - ~/devices.db:/app/devices.db
    restart: unless-stopped
